global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'token_estimator'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - "/etc/prometheus/rules.yml"